" If Vim Plug is not installed, install it
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Activate syntax highlighting
syntax enable

" Not sure what to comment here...
set nocompatible
filetype plugin on

call plug#begin('~/.vim/plugged')

" Directory access with '-'
Plug 'tpope/vim-vinegar'

" Emmet keyboard shortcuts
Plug 'mattn/emmet-vim'


" Status bar
Plug 'vim-airline/vim-airline'

" Theme
Plug 'whatyouhide/vim-gotham'

" Language support
Plug 'sheerun/vim-polyglot'


" Alchemist (Elixir) tools
Plug 'slashmili/alchemist.vim'
let g:alchemist_tag_disable = 1


" Git diffs
Plug 'airblade/vim-gitgutter'


" Split vim and tmux panes with Ctrl + direction
Plug 'christoomey/vim-tmux-navigator'


" Search
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': '.install --all' }
Plug 'junegunn/fzf.vim'

call plug#end()


" Set colourscheme
colorscheme gotham

" Use csscomplete function (Plug)
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS noci

" Allow vim<>system clipboard
set clipboard=unnamed

" Remap leader to spacebar
let mapleader = "\<Space>"

" Map 'save' to leader
nnoremap <Leader>w :w<CR>

" Map <Leader>, to clear search
map <Leader>, :noh<CR>

" Map 'FZF :Files' to leader
nnoremap <Leader>ff :Files<CR>
nnoremap <Leader>pf :GFiles<CR>

" Use <Space> + wv/wh to create splits
nnoremap <Leader>wv :vsplit<CR>
nnoremap <Leader>wh :split<CR>

" Open :Explore with <Space>e
nnoremap <Leader>e :Vexplore<CR>

" Show invisibles (tabs and trailing spaces)
set list
set listchars=tab:»-,trail:·

" Remap <Esc> to something faster
imap jk <esc>

set number relativenumber
set splitbelow
set splitright
set showmatch
set ruler
set expandtab
set tabstop=2
set shiftwidth=2
